"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var film_1 = require("./film");
var trailer_1 = require("./trailer");
var title = '12 Rounds 3: Lockdown';
var release = 'Fri, 11 Sep 2015 00:00:00 -0700';
var studio = 'Lionsgate';
var poster = 'http://trailers.apple.com/trailers/lions_gate/12rounds3lockdown/images/poster.jpg';
var location = '/trailers/lions_gate/12rounds3lockdown/';
var rating = 'R';
var genre = '["Action and Adventure"]';
var directors = 'Stephen Reynolds';
var postDate = '12 Rounds 3: Lockdown';
var url = 'Fri, 11 Sep 2015 00:00:00 -0700';
var type = 'Lionsgate';
var exclusive = false;
var hd = true;
var trailer = new trailer_1.Trailer(postDate, url, type, exclusive, hd);
var film = new film_1.Film(title, release, studio, poster, location, rating, genre, directors, trailer);
console.log("FILM :\n    titre : " + film.title + "\n    release : " + film.release + "\n    studio : " + film.studio + "\n    poster : " + film.poster + "\n    location : " + film.location + "\n    rating : " + film.rating + "\n    genre : " + film.genre + "\n    directors : " + film.directors + "\n    Trailers :\n        postDate : " + film.trailer.postDate + "\n        url : " + film.trailer.url + "\n        type : " + film.trailer.type + "\n        exclusive : " + film.trailer.exclusive + "\n        hd : " + film.trailer.hd);
//# sourceMappingURL=index.js.map